Game/Config/DefaultGame.ini
All runs of this project can only have at most 16 players, as the MaxPlayers setting in the engine’s BaseGame.ini is never being overwritten.
See https://improbableio.atlassian.net/browse/UNR-2898 for context.
@danielimprobable @m-samiec @spatialos/develop-unreal
=> UNR-2898 - Update max player/spectator number

Game/Config/DefaultEngine.ini, Game/Source/GDKTestGyms/GDKTestGymsGameInstance.cpp, Game/Source/GDKTestGyms/GDKTestGymsGameInstance.h, LaunchSimClient.bat
FPS output is required by NFR pipeline to deduce the health of workers.
=> Add fps output, used by NFR pipeline

spatial/workers/unreal/spatialos.UnrealWorker.worker.json
This PR is is one of four related ones (from major to minor):
* [NFR Framework](https://github.com/improbable/nfr-benchmark-pipeline/pull/116)
* [UnrealGDK](https://github.com/spatialos/UnrealGDK/pull/1975)
* [TestGymBuildkite](https://github.com/improbable/TestGymBuildKite/pull/57)
* [UnrealGDKTestGyms](https://github.com/spatialos/UnrealGDKTestGyms/pull/68)
These PRs implement/accommodate two changes to NFR latency testing:
**New required "trace descriptions" parameter**
Users now have to supply "trace descriptions". The framework will now only include traces whose root span names include one of the user-cupplied trace descriptions. This gives users more control over what exact interactions they want to log.
**Span name format change**
The format of span names has been updated so that …
=> Feature/GV-329 New NFR parameter and new span name format

Game/Config/DefaultSpatialGDKSettings.ini
The TestGym BK job currently parses unique entries in each ini file, which break array values, and thus qbi-f in our test framework. This change works around the issue by enabling unique keys for our values (one with `+` one without). 
Will be fixed correctly with - https://improbableio.atlassian.net/browse/UNR-3541
=> Fix QBI-F results

Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp, Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h, Game/Source/GDKTestGyms/GDKTestGymsGameInstance.h, Game/Source/GDKTestGyms/Private/NFRConstants.cpp, Game/Source/GDKTestGyms/Private/UserExperienceReporter.cpp, Game/Source/GDKTestGyms/Public/NFRConstants.h
This is what we want to achieve:
- In spatial we want to "fail" without any delay. This means that we will receive useful logs throughout the lifetime of a worker. We will rely on the initial delays set in NFR yaml files to ensure these metric do not fail tests too early
- In native we will not report these logs before a certain timer. This is due to the fact that the logs are used to fail NFR runs. 
All timers have been added to NFRConstants for consistency.
=> [UNR-3678][MS] Consistent metric timers for GDK and native

spatial/workers/improbable/spatialos.SimulatedPlayerCoordinator.worker.json
With UE 4.25 using an invalid address leads to the connection being closed. Let's use a valid IP address to fix this. we are not using this address anyway, so it can just be localhost.
=> UNR-3925: Use valid ip address

Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp, Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
Count all actual players of all workers.
------------------------------------
For zoning. some players would be in both workers when crossing the boundary.
If using UnrealActivePlayers and combine them together would be more then TotalPlayers.
The metrics of unrealgdk-nfr only from 1 worker. Combine all the players(HasAuthority()) of all workers is necessary.
------------------------------------
Jira ticket:https://improbableio.atlassian.net/browse/UNR-4143
=> UNR-4143 Add UnrealTotalAuthoritativePlayers for total players of all workers

Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp, Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
To keep the nfr testing with the same expectations both on zoning and none-zoning.
Add a new metric is not necessary.
------------------------------------------
Count the authoritative players from UUserExperienceReporter with HasAuthority() check.
GetNumPlayers() is necessary for analyzing the log of UnrealWorker, So I restore it back.
Jira ticket:
https://improbableio.atlassian.net/browse/UNR-4226
=> UNR-4226 Change UnrealTotalAuthoritativePlayers to UnrealActivePlayers

Game/Source/GDKTestGyms/GDKTestGyms.Build.cs, Game/Source/GDKTestGyms/GDKTestGymsCharacter.cpp, Game/Source/GDKTestGyms/GDKTestGymsGameInstance.cpp, Game/Source/GDKTestGyms/GDKTestGymsGameInstance.h, Game/Source/GDKTestGyms/Private/NFRConstants.cpp, Game/Source/GDKTestGyms/Private/UserExperienceComponent.cpp, Game/Source/GDKTestGyms/Private/UserExperienceReporter.cpp
had a bunch of problems with building the GDK test gyms because of this legacy property thing. This PR cleans up includes such that we can turn it off, and then also turns it off. I no longer get "debug compilation record too long" errors when compiling now. (at least, so far)
=> fix long debug record compilation issues

Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp, Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h, Game/Source/GDKTestGyms/Private/NFRConstants.cpp, Game/Source/GDKTestGyms/Public/NFRConstants.h
For zoning specific overhead, add a new metric UnrealActorMigration.
1) Count all the Actors which HasAuthority() in each tick
2) Calculate the delta with the count of the last frame
3) sum all the abs of delta in 5 minutes as MigrationOfCurrentWorker
4) sum all the MigrationOfCurrentWorker from all workers as the value of the metric
Added a new WorkerFlag that changes how Migration is verified and prints the associated logs in case of failure.
Changed Migration to every frame instead of the previous every 9000 frames.
Added DelayTimer to avoid statistical errors caused by the players not being fully connected.
Changed the reporting of Migration to only for changes.
=> UNR-4045 Add UnrealActorMigration as a new metric for zoning-nfr 

Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp, Game/Source/GDKTestGyms/BenchmarkGymGameMode.h, Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp, Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h, Game/Source/GDKTestGyms/Private/NFRConstants.cpp, Game/Source/GDKTestGyms/Public/NFRConstants.h
Sometimes, there are some 1 or 2 clients lost in the max-player scenario of zoning-NFR. 
After investigating the client_stayed_connection issue. I found the value of total players on all the workers is not a stable value.
As the picture is shown on the [ticket](https://improbableio.atlassian.net/browse/UNR-4426).
So we decide to change the total player number as an average value for the last frame and the current frame.
It should very approach the value we expected. 
Sometimes it was 1.xx less than expectation. So we set the expectation of max-player as 2.
BTW:
1. Change the player number check to a valid check. So we can have the same value of expectation with BuildKite.
2. Change the timer for the delay, check and report. to make sure when we start to check, the worker has enough time …
=> UNR-4426 fix connected clients expectation synchronization issue

Game/Source/GDKTestGyms/Private/TestGymsReplicationGraph.cpp
This warning gets hit for PlayerState and PlayerController, but doesn't actually affect the behavior, so it shouldn't be a warning.
=> Downgrade warning: 'RouteAddNetworkActorToNodes: Not Routed'

Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp, Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
For CPU usage investigating, we can enable the Unreal stat profile via WorkerFlag.
`start_profile_after_beginning` means how long `stat startfile` after game beginning in seconds.
`stop_profile_after_startfile` means how long `stat stopfile` after `stat startfile` in seconds.
Also, support the command line with `StartProfileAfterBeginning` and `StopProfileAfterStartfile` as the same as above.
The output stat file path is `data\workers\UnrealWorker\GDKTestGyms\Saved\Profiling\UnrealStats` and the file name is base on WorkerId.
Jira ticket:https://improbableio.atlassian.net/browse/UNR-4475
Successful build:https://buildkite.com/improbable/unrealgdk-nfr/builds/3194
=> UNR-4427 enable stat profile via workerflag

USER_MANUAL.md
* Clarifies the ReplicatedStartupActor gym steps.
* Changes 1,2,3 lists to 1,1,1 formatting. I rendered these changes to make sure they look correct.
=> Clarify the ReplicatedStartupActor gym steps.

USER_MANUAL.md
Adds a known issue note so that users of the Test Gyms do not  waste their time testing something we know is non-functional.
=> Note that ServerTravel is not suppoted.

USER_MANUAL.md
* Clarifies `DestroyStartupActorGym` test gym steps.
* I ran these steps to validate that they are correct.
=> Clarify DestroyStartupActorGym test gym steps.

USER_MANUAL.md
* Clarifies `Latency gym` steps, in particular, that manual QA is not required.
=> Clarify Latency gym steps.

Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp, Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp, Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
Using "NumSpawnZones" to distribute spawn clusters. This is just to ensure we have parity between offloaded, non offloaded and native tests.
NFRBuildkite PR: https://github.com/improbable/TestGymBuildkite/pull/219
BK Test: https://buildkite.com/improbable/unrealgdk-nfr/builds/3544
=> Fixing flake in NFRs to do with player count

USER_MANUAL.md
* Clarifies `Client Travel gym` test steps.
* I ran these steps to validate that they are correct.
=> Clarifies `Client Travel gym` test steps.

Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp, Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
We count the PlayerCharacter which has `UUserExperienceReporter` as the expectation of client_stayed_connection before, as the understanding updated, we think to count the PlayerController as the expectation should be better for us to know the connection count, not the actor count.
The successful build is:https://buildkite.com/improbable/unrealgdk-nfr/builds/3564
the old branch of the test is out-to-date, this PR just `merge --squash` from that branch
=> UNR-4874 Count auth PlayerController for client_stayed_connection check

Game/Config/DefaultEngine.ini
Audio logs were spamming our tests and making the results un-readable. This simply prevents that spam.
Example before: https://buildkite.com/improbable/unrealgdk-premerge/builds/22314
Example after: https://buildkite.com/improbable/unrealgdk-premerge/builds/22325
=> Disable audio logs

Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
Fix that is required by https://github.com/spatialos/UnrealGDK/pull/2965, which cleans up the SpatialNetDriver header with more forward declarations.
=> Add missing header

Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp, Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
put all the flag codes into STATS macro to fix compile error and avoid the extra Tick() cost in shipping.
waiting for NFR test: https://buildkite.com/improbable/unrealgdk-nfr/builds/4120
=> [Fix] Shut down Memreport Flag in Shipping build

Game/Config/DefaultInput.ini, Game/GDKTestGyms.uproject
* I made the plugin changes via the **Edit** > **Plugins** flow. I didn't manually edit the `.uproject` file.
* These changes non-destructively disable Magic Leap.
* They stop these errors triggering when you open the project or generate schema:
`Warning: MLSDK not found.  This likely means the MLSDK environment variable is not set.`
`Warning: VR disabled because ZI is not enabled.`
* I tested these before and after making the changes.
* I also deleted `+ActionMappings=(ActionName="ResetVR",Key=MotionController_Left_Grip1,bShift=False,bCtrl=False,bAlt=False,bCmd=False)`
* Because it was triggering:
* `LogInput: Warning: Action ResetVR uses invalid key MotionController_Left_Grip1.`
* `LogInput: Warning: Use -RemoveInvalidKeys to remove instances of these keys from the action mapping.`
=> Disable Magic Leap plugins + Obsolete VR inputs plugins that were triggering WARNs

.buildkite/premerge.steps.yaml
Labels are used to identify which builds are required by GH. By generating unique labels for each branch we were spamming our GH UI with new builds to watch and also made it impossible to make the old-ci non-required without removing it. This fixes that.
=> Fix labels and messages. Make new ci required. 

.buildkite/premerge.steps.yaml
Realised there's no point of running old CI for TestGyms as all it does is call new CI for GDK.
The new implementation calls the UnrealGDKBuild repo as desired (new ci) and so no need to do it twice.
=> Remove old CI

Game/Config/DefaultGame.ini
Modified `DefaultGame.ini` to whitelist files that were previously throwing WARNs when building assemblies for cloud deployments.
None.
* I cloud deployed after I implemented this fix in order to ensure that I hadn't broken that functionality.
* I confirmed that the WARNs are gone.
Not needed.
@mironec
=> Fix "The config file will be staged, but is not whitelisted or blacklisted" WARNs

Game/Source/GDKTestGyms/Private/DeterministicBlackboardValues.cpp
Added the actor name to this log message, as it provided no actionable information previously. Now at least it possible to find other messages related to this actor (such as creation) in the event that something unexpected happens.
While working on uptime something came up where this message was an indicator of a problem but it lacked enough detail to be useful.
=> UNR-5541 - Improve the log message

Game/Config/MapSettingsOverrides/TestOverridesSpatialEventTracingTests.ini, Game/Config/MapSettingsOverrides/TestOverridesSpatialEventTracingZoningTests.ini
`SpatialOSCommandLineLaunchFlags` is no longer required since the runtime switched from using cli flags to the generated config (which is based off the GDK setting for local/cloud workflows)
=> Remove old CLI flags from test override 

Game/Source/GDKTestGyms/Private/DeterministicBlackboardValues.cpp, Game/Source/GDKTestGyms/Public/DeterministicBlackboardValues.h
Fix generate schema error.
Replace `Handover` with `Cond_ServerOnly` tag.
There was a time gap between `UNR-5447` and `UNR-5543`, so they missed it.
When raise PR, there was a pre merge check, which did not include another PR which was in review.
=> Fix generate schema error by replace handover with server only tag.

.buildkite/premerge.definition.yaml
For full description, see: https://github.com/spatialos/UnrealGDK/pull/3176
=> Makes `dry-run/*`, `skip-ci/`, `doc/*` &  `docs/*` branches exempt from premerge

Game/Config/DefaultGame.ini
Clients now send server moves at a frequency no greater than server tick rate.
Test run - https://buildkite.com/improbable/unrealgdk-nfr/builds/5653
=> Decrease server move frequency

.buildkite/premerge.definition.yaml
Reverts: https://github.com/spatialos/UnrealGDKTestGyms/pull/418
We were forced to pick a [different approach](https://improbableio.atlassian.net/browse/UNR-4903?focusedCommentId=451317).
The `circle ci pipeline check` output for this change is:
```ERRO Pipeline not as expected, would apply the following diff:
@@ -4,10 +4,10 @@
ID: ""
Name: unrealgdktestgyms-premerge
ProviderSettings:
-  branch_configuration: '!dry-run/* !skip-ci/* !doc/* !docs/*'
+  branch_configuration: ""
publish_commit_status_per_step: true
-  pull_request_branch_filter_configuration: '!dry-run/* !skip-ci/* !doc/* !docs/*'
-  pull_request_branch_filter_enabled: true
+  pull_request_branch_filter_configuration: ""
+  pull_request_branch_filter_enabled: false
Repository:
url: …
```
=> Revert #418

USER_MANUAL.md
Small fix for the gameplay debugger non-spatial test notes, which mentions (incorrectly) multiple servers.
=> [UNR-5789] Fix gameplay debugger non-spatial-specific test notes

Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp, Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
Previously we were allowing failures to go unreported if they weren't the last actor count checked in Spatial runs.
=> Fix checks for multiple actor counts

Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
We've seen failures in the migration metric in health deployments. For now, reduce the amount of required migration. 
todo ticket - https://improbableio.atlassian.net/browse/UNR-5825
=> Reduce required migration in NFRs
