- Game/Config/DefaultSpatialGDKSettings.ini
> Reset sensible spatial gdk defaults for NFR pipeline

- Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
Simulated clients will move again
> Set simulated pawn class

- BuildProject.bat
Related GDK change: spatialos/UnrealGDK#1842
> [UNR-2978][MS] Removing building of SimPlayers from BuildWorker.bat

- Game/Source/GDKTestGyms/GDKTestGymsGameInstance.cpp
Removing fps cap because egress regression
> Removing max FPS

- Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
- Game/Source/GDKTestGyms/BenchmarkGymGameMode.h
Spawning NPCs 1 at a time to avoid a huge frame spike
> Spawn NPCs slower

- Game/Config/DefaultSpatialGDKSettings.ini
> Enable NCD interest

- Game/Source/GDKTestGyms/Private/SpatialLockingActorComponent.cpp
- spatial/spatialos.json
Master now uses 14.5 - update accordingly.
> Update to 14.5

- Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
- Game/Source/GDKTestGyms/BenchmarkGymGameMode.h
Adding spawned players metric to NFR tests and updating log
> Adding spawned players metric for GDK

- Game/Source/GDKTestGyms/GDKTestGymsGameInstance.cpp
- Game/Source/GDKTestGyms/GDKTestGymsGameInstance.h
NFRs occasionally fail with blanket connection failures - add retry logic
https://improbableio.atlassian.net/browse/UNR-3474
> Add retry conneciton logic

- Game/Source/GDKTestGyms/GDKTestGymsGameInstance.cpp
- Game/Source/GDKTestGyms/GDKTestGymsGameInstance.h
Updating the FPS metric to use a 2 minute window similar to the GDK metric
> Updating FPS metric to match GDK

- DeployGame.bat
- spatial/default_launch.json
- spatial/one_worker_test.json
- spatial/two_worker_test.json
Update the pinned runtime and launch configs to the same as ExampleProject
> Update pinned runtime and templates

- USER_MANUAL.md
Updated the USER_MANUAL to reflect that there is an automated test for the NetReference and for the ReplicatedStartupActor Gyms.
> Updated the USER_MANUAL

- Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
- Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
- Game/Source/GDKTestGyms/Private/UserExperienceReporter.cpp
- Game/Source/GDKTestGyms/Public/UserExperienceReporter.h
After investigating the RTT metric of UnrealGDKTestGyms, I found some variables had been named as second but it was millisecond in actual.
So I make this PR to change it.
> Change RTT and UpdateTimeDelta unit to milisecond

- Game/Source/GDKTestGyms/BenchmarkGymGameMode.cpp
- Game/Source/GDKTestGyms/BenchmarkGymGameMode.h
- Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.cpp
- Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
feature/better-api-worker-flag-updates
https://github.com/spatialos/UnrealGDK/pull/2688
> UNR-4165 updated gym to confirm to renamed api in GDK plugin 

- USER_MANUAL.md
Tell test users to generate schema and snapshot.
> Tell test users to generate schema and snapshot.

- USER_MANUAL.md
* Clarifies `Teleporting gym` test steps.
* I ran these steps to validate that they are correct.
> Clarify Teleporting gym steps

- USER_MANUAL.md
* Clarifies `GameplayCuesMap` test steps.
* I ran these steps to validate that they are correct.
> Clarify `GameplayCuesMap` steps.

- USER_MANUAL.md
* @m-samiec wrote these tests.
* I ran them. They work
* I edited the language and structure slightly.
* I rendered the markdown to ensure that it looks correct.
> Test: Snapshot reloading.

- spatial/default_launch.json
Setup gym UnrealClient to have limited permissions in launch config.
See: https://improbable.slack.com/archives/CCBNTFAHW/p1611683455021500
> UNR-4915 setup gym UnrealClient to have limited permissions in launch config

- LaunchSpatial.bat
- spatial/spatialos.json
Update all settings files to run runtime 15.0.1
https://github.com/improbableio/UnrealEngine/pull/836
https://github.com/improbableio/UnrealEngine/pull/837
https://github.com/spatialos/UnrealGDKExampleProject/pull/251
https://github.com/improbable/UnrealGDKEngineNetTest/pull/86
https://github.com/spatialos/UnrealGDK/pull/2959
https://github.com/spatialos/UnrealGDKTestGyms/pull/327
> UNR-5163 updated runtime to 15.0.1

- .buildkite/premerge.steps.yaml
CI versioning changes:
https://github.com/spatialos/UnrealGDKTestGyms/pull/347
https://github.com/spatialos/UnrealGDK/pull/3015
https://github.com/improbableio/UnrealEngine/pull/855
https://github.com/improbableio/UnrealEngine/pull/852
> [UNR-5150] Update premerge.steps.yaml

- USER_MANUAL.md
Makes the  Server to server Take Damage RPC gym more comprehensible
> Make the Server Take Damage RPC gym more comprehensible

- .buildkite/premerge.steps.yaml
We didn't implement this yet, fixes it.
> Allow branch overriding for engine and GDK

- .buildkite/premerge.steps.yaml
Moving forward to 1.3.
Fixes the floating head bug and enables NFR builds
> Updating to new CI version 1.3

- Game/Source/GDKTestGyms/BenchmarkGymGameModeBase.h
> Explicitly initialize ActorCount variables in constructor

- .buildkite/premerge.steps.yaml
Complementary PR to improbableio.atlassian.net/browse/UNR-5765
> Update default CI branch to 0.14.0-rc

- Game/Config/NFROverrides/DefaultEngine.diff.ini
- Game/Config/NFROverrides/DefaultSpatialGDKSettings-CN.diff.ini
- Game/Config/NFROverrides/DefaultSpatialGDKSettings.diff.ini
Move the ini overrides to TestGyms to make NFR modifications easier
> Move ini file overrides

- Game/Source/GDKTestGyms/Private/TestGymsReplicationGraph.cpp
Required PR for https://github.com/spatialos/UnrealGDK/pull/3285
> Fix for nonspatialized classes in Rep Graph

- spatial/spatialos.json
**UE 426**: https://github.com/improbableio/UnrealEngine/pull/1039
**UE 425**: https://github.com/improbableio/UnrealEngine/pull/1040
**GDK**: https://github.com/spatialos/UnrealGDK/pull/3308
**Example**: https://github.com/spatialos/UnrealGDKExampleProject/pull/298
**Test Gyms**: https://github.com/spatialos/UnrealGDKTestGyms/pull/465
**Engine Net Test**: https://github.com/improbable/UnrealGDKEngineNetTest/pull/98
**NFR Benchmark**: https://github.com/improbable/nfr-benchmark-pipeline/pull/181
> [UNR-5875] upgrade to worker sdk 15.3.1

- README.md
Remade https://github.com/spatialos/UnrealGDKTestGyms/pull/20 with correct user permissions
> Update user manual link
